### PR TITLE
Upgrade supported Symfony versions

### PR DESCRIPTION
**Pull request by keichinger**
Upgrade minimum versions to require ^3.4 or ^4.1

### CODE REVIEW

**Comment by mangoischke** [comment]
I want to suggest that, if you are upgrading the minimum Symfony versions, you could enable autowiring for our services since this is supported since Symfony 3.3.

https://symfony.com/doc/3.3/service_container/autowiring.html

**Comment by apfelbox** [comment]
What new functionality would that give us?

**Comment by mangoischke** [comment]
In newer projects it is common practice to register and autowire nearly all services in `/src/`.
If you want to use one of these services you need to explicitly set them as a parameter which would be extra work.

**Comment by apfelbox** [comment]
This is the other way round.

We can change our service names so that you can autowire these services in your project. What we won't be doing is using autowiring in this library itself, as this is officially discouraged.

Autowiring is something the consumer does, not the producer.

**Comment by mangoischke** [comment]
That's actually what I requested.
Sorry, for not being clear enough.

**Comment by apfelbox** [comment]
This bundle will soon be rewritten for Algolia, so I am closing this one.

Thanks for your work, though! 🎈

**Pull request closed without merging**
